apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: elestio/pgadmin:latest
        env:
          - name: PGADMIN_DEFAULT_EMAIL
            value: "paplix.dev@gmail.com"
          - name: PGADMIN_LISTEN_PORT
            value: "8080"
          - name: PGADMIN_DEFAULT_PASSWORD
            value: "Luqman"
           # valueFrom:
            #  secretKeyRef:
             #   name: pgadmin-secret
              #  key: ADMIN_PASSWORD

        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
