apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  labels:
    app: postgres
 # volumeClaimTemplates:
#  - metadata:
  #    name: pgpvcc
   # spec:
    #  accessModes: [ "ReadWriteOnce" ]
     # storageClassName: pg
      #resources:
       # requests:
        #  storage: 1Gi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: pg
          persistentVolumeClaim:
            claimName: pgpvc
      containers:
      - name: postgres
        image: postgres:12.19
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: pg
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: pgadmin-config
                key: POSTGRES_USER

          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pgadmin-secret
                key: POSTGRES_PASSWORD

          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: pgadmin-config
                key: POSTGRES_DB

        ports:
        - containerPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
 # type: ClusterIP
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None
