apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgpvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: pg
