apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  # property-like keys; each key maps to a simple value
  MONGO_INITDB_ROOT_USERNAME: "root"
  ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
