apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
  labels:
    app: express
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: "root"
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: "example"
        - name: ME_CONFIG_MONGODB_URL
          value: mongodb://root:example@mongo-service:27017/
        - name: ME_CONFIG_BASICAUTH
          value: "false"
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  type: LoadBalancer
  selector:
    app: express
  ports:
    - port: 8081
      targetPort: 8081
