apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgpv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: pg
  hostPath:
    path: "/home/arman/dbk8/mongo/db"
