apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo-service
spec:
  type: LoadBalancer
  ports:
  - port: 27017
    targetPort: 27017
    name: mongo-service
  selector:
    app: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo-service
  replicas: 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "example"
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongopath
          mountPath: /etc/mongo
  volumeClaimTemplates:
  - metadata:
      name: mongopath
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "pg"
      resources:
        requests:
          storage: 1Gi
